services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./docker/crm/
    command: bash -c "while !</dev/tcp/db/${DATABASE_PORT}; do sleep 1; done; python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/code
    ports:
      - "${WEB_SERVER_PORT}:8000"
    depends_on:
      - db
volumes:
  pgdata:
