# Generated by Django 3.2 on 2021-04-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_code', models.TextField(max_length=10)),
                ('aircraft_model', models.TextField(max_length=255)),
                ('mtow_weight_kg', models.PositiveIntegerField()),
                ('max_payload_kg', models.PositiveIntegerField()),
                ('range_of_flight_km', models.PositiveSmallIntegerField()),
                ('cargo_volume_m', models.PositiveSmallIntegerField()),
                ('fuel_capacity_kg', models.PositiveIntegerField()),
                ('takeoff_length_m', models.PositiveIntegerField()),
                ('landing_length_m', models.PositiveIntegerField()),
                ('speed_kmh', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=3, unique=True)),
                ('icao', models.CharField(max_length=4, unique=True)),
                ('name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('altitude', models.IntegerField()),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('category', models.SmallIntegerField(choices=[(0, 'I'), (1, 'II'), (2, 'IIIA'), (3, 'IIIB')])),
                ('is_active', models.BooleanField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_departure_time', models.TimeField()),
                ('planning_arrival_time', models.TimeField()),
                ('flight_code', models.CharField(max_length=255, unique=True)),
                ('passanger_capacity', models.PositiveSmallIntegerField()),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing FPM'), (2, 'Error FPM'), (3, 'Pending EPM'), (4, 'Processing EPM'), (5, 'Error EPM'), (6, 'Success')], default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='crm.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_airport', to='crm.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_departure_datetime', models.DateTimeField()),
                ('planning_arrival_datetime', models.DateTimeField()),
                ('actual_departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('has_arrived', models.BooleanField()),
                ('actual_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.airport')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.aircraft')),
                ('flight_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.flightplan')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_start', models.DateTimeField(null=True)),
                ('disability_end', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=1024)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.occupation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AircraftLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField()),
                ('event_description', models.TextField()),
                ('event_type', models.SmallIntegerField(choices=[(0, 'Can fly with passengers'), (1, 'Can fly without passengers'), (2, "Can't fly at all")])),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftDynamicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy_class_cap', models.PositiveSmallIntegerField()),
                ('business_class_cap', models.PositiveSmallIntegerField()),
                ('first_class_cap', models.PositiveSmallIntegerField()),
                ('fuel_remaining_kg', models.PositiveIntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftDeviceLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=1024)),
                ('latest_update', models.DateTimeField()),
                ('max_operation_time_h', models.PositiveIntegerField()),
                ('max_operation_cycles', models.PositiveIntegerField()),
                ('total_operation_time_h', models.PositiveIntegerField()),
                ('total_operation_cycles', models.PositiveIntegerField()),
                ('after_service_time_h', models.PositiveIntegerField()),
                ('after_service_cycles', models.PositiveIntegerField()),
                ('service_time_period_h', models.PositiveIntegerField()),
                ('service_cycles_period', models.PositiveIntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.aircraft')),
            ],
        ),
    ]
