# Generated by Django 3.1.7 on 2021-03-16 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_code', models.TextField(max_length=10)),
                ('aircraft_model', models.TextField(max_length=255)),
                ('mtow_weight_kg', models.PositiveIntegerField()),
                ('max_payload_kg', models.PositiveIntegerField()),
                ('range_of_flight_km', models.PositiveSmallIntegerField()),
                ('cargo_volume_m', models.PositiveSmallIntegerField()),
                ('fuel_capacity_kg', models.PositiveIntegerField()),
                ('takeoff_length_m', models.PositiveIntegerField()),
                ('landing_length_m', models.PositiveIntegerField()),
                ('speed_kmh', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeelog',
            name='log_date',
        ),
        migrations.AddField(
            model_name='employeelog',
            name='disability_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeelog',
            name='disability_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AircraftLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField()),
                ('event_description', models.TextField()),
                ('is_operational', models.BooleanField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftDynamicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy_class_cap', models.PositiveSmallIntegerField()),
                ('business_class_cap', models.PositiveSmallIntegerField()),
                ('first_class_cap', models.PositiveSmallIntegerField()),
                ('fuel_remaining_kg', models.PositiveIntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftDeviceLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=1024)),
                ('latest_update', models.DateTimeField()),
                ('max_operation_time', models.DurationField()),
                ('max_operation_cycles', models.PositiveIntegerField()),
                ('total_operation_time', models.DurationField()),
                ('total_operation_cycles', models.PositiveIntegerField()),
                ('after_service_time', models.DurationField()),
                ('after_service_cycles', models.PositiveIntegerField()),
                ('service_time_period', models.DurationField()),
                ('service_cycles_period', models.PositiveIntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.aircraft'),
            preserve_default=False,
        ),
    ]
