# Generated by Django 3.2 on 2021-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='has_arrived',
        ),
        migrations.AddField(
            model_name='flight',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
