# Generated by Django 3.2 on 2021-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210410_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='employees',
            field=models.ManyToManyField(to='crm.Employee'),
        ),
    ]
