# Generated by Django 3.1.7 on 2021-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210316_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelog',
            name='disability_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employeelog',
            name='disability_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
