# Generated by Django 3.2 on 2021-04-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210420_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulersConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_flight_delay_minutes', models.PositiveSmallIntegerField()),
                ('max_flight_generation_attempts', models.PositiveSmallIntegerField()),
                ('flight_generation_timeout_s', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
