# Generated by Django 3.2 on 2021-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_schedulersconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_past_flights_time', models.DurationField()),
                ('show_future_flights_time', models.DurationField()),
                ('warning_schedule_delay_time', models.DurationField()),
                ('warning_arrival_delay_time', models.DurationField()),
                ('warning_arrival_shifted_time', models.DurationField()),
                ('min_between_flights_delay_minutes', models.DurationField()),
                ('max_flight_generation_attempts', models.PositiveSmallIntegerField()),
                ('flight_generation_timeout', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='SchedulersConfig',
        ),
    ]
