# Generated by Django 3.2 on 2021-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210425_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'OK'), (1, 'NO-SHOW'), (2, 'LEAVE UNPAID'), (3, 'LEAVE PAID'), (4, 'LEAVE SICK')], default=0),
        ),
        migrations.AlterField(
            model_name='employeelog',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
