# Generated by Django 3.2.3 on 2021-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210513_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'OK'), (1, 'NO-SHOW'), (2, 'LEAVE UNPAID'), (3, 'LEAVE PAID'), (4, 'LEAVE SICK')], default=(0, 'OK')),
        ),
    ]
