name: Coding style checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build app
    - name: Run pre-commit checks
      run: docker-compose run --no-deps app pre-commit run --all-files
