name: Coding style checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./docker/crm/Dockerfile -t airline-crm:latest
    - name: Run tests
      run: docker run --rm -e SECRET_KEY=test airline-crm:latest pre-commit run --all-files
