name: Django tests

on:
  push:
    branches: [ workflow-experiments ]

env:
    SECRET_KEY: "not empty"
    DATABASE_USER: "postgres"
    DATABASE_PASS: "postgres"
    DATABASE_DB: "postgres"
    DATABASE_PORT: 5432
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: python version
      run: python --version
    - name: python3 version
      run: python3 --version
