name: Django tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build app
    - name: Run tests
      run: docker-compose run --no-deps app python manage.py test
