name: Django tests

on:
  push:
    branches: [ workflow-experiments ]

env:
    SECRET_KEY: "not empty"
    DATABASE_USER: "postgres"
    DATABASE_PASS: "postgres"
    DATABASE_DB: "postgres"
    DATABASE_PORT: 5432
jobs:
  build:
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASS }}
          POSTGRES_DB: ${{ env.DATABASE_DB }}
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Installing dependencies
      run: pip install -r ./requirements.txt
    - name: python version
      run: python --version
    - name: python3 version
      run: python3 --version
    - name: Run migrations
      run: python ./manage.py migrate
    - name: Run tests
      run: python ./manage.py test
